# Generated by Django 5.2.11 on 2026-02-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_dataset_file_project_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='Unknown Model', max_length=250)),
                ('year', models.IntegerField(default=2020)),
                ('price', models.FloatField()),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('mileage', models.FloatField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='projects.project')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='projects.company')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='projects.fueltype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='projects.region')),
            ],
        ),
    ]
