# Generated by Django 5.2.11 on 2026-02-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activity_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pro.jpg', upload_to='profiles/'),
        ),
    ]
