# Generated by Django 5.2.11 on 2026-02-27 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#0f172a', max_length=50)),
                ('primary_color', models.CharField(default='#3b82f6', max_length=50)),
                ('layout_mode', models.CharField(default='modern', max_length=20)),
                ('is_dark_mode', models.BooleanField(default=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='themes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
