# Generated by Django 5.2.11 on 2026-03-11 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_workspacemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_goal', models.CharField(choices=[('Recruitment', 'Recruitment Analytics'), ('Sales', 'Sales Analytics'), ('General', 'General Data Analysis')], default='General', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.company'),
        ),
    ]
